# Generated by Django 3.2.5 on 2021-07-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('re_password', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('Middlename', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('project_url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('re_password', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
